version: '2.1'

services:

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./heimdall:/config
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    env_file:
      - duckdns-conf/.env
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped

  my-graphql:
    build:
      context: ./graphql-conf
      dockerfile: dockerfile
    ports:
      - 4000:4000
    restart: unless-stopped

  db-sql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  admin:
    image: phpmyadmin:latest 
    container_name: admin 
    restart: always 
    environment:
      - PMA ARBITRARY=1 ports="8080:80"

  jira:
    image: atlassian/jira-software:latest
    restart: always
    links:
      - db-sql
    volumes:
      - jira-data:/var/atlassian/jira
    ports:
      - "8080:8080"

  confluence:
    image: atlassian/confluence-server:latest
    restart: always
    ports:
      - "8090:8090"

  googleCloud:
    image: google/cloud-sdk:latest
    restart: always

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"

volumes:
  mongo:
  db:
  obsidianVaults:
  obsidianConfig:
  jira-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  wordpress:
