FROM node:16-alpine
RUN apk --no-cache add git
RUN git clone https://github.com/defless/GraphQL-demo.git
WORKDIR /GraphQL-demo
RUN npm install --force

ENV HOST=0.0.0.0
EXPOSE 4000

CMD ["npm", "run", "start"]